- hosts: all
  become: true
  become_user: root
  tasks:
          - name: Set authorized key taken from file
            ansible.posix.authorized_key:
              user: "{{ SSHUSER  }}"
              state: present
              key: "{{ lookup('file', SSHPUBKEYPATH) }}"
