
== SBOM
:toc:
:source-highlighter: rouge

https://www.suse.com/support/kb/doc/?id=000021411

https://www.suse.com/c/suse-linux-enterprise-and-sbom-support/


[source,shell]
----
cat << EOF > /tmp/suse.pem
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAxfZssLE2jeY1swPb5WGe
8C/FWKmIxlGLm9amCNdgheAn8RzuM8slA+TJefAQnrUnC4Qn9ykjQZjH6o2e2ueA
KFdgOdHnlS2d6lETB8dd4O8HYDJx0CEk2SCbAKVuzLbcbP4ug/QDc+Bm8ldxfc+D
GnLVRAt85brSTnfgOHY1PbQ1JAV+ByibbjCZuFmw4gIkMzeiy3M4wJZwblFM4a3s
X2bW/6GWaGz6AMOjCyAPI6shyG5wHZM7OvJJ8lfhXRTZo4Cc5qC0Nyq9Xu3O6DmV
opIajhHc36kdcetmd7TB5OSbQZCLyReAF75LV74y8960+44NptR62hdw1ovCJMfV
mU6m+k/MsN8AIyRFR6dNF9wTOKi67OpPtybiRufCfMvD4VEeoINzEJytToq2XGSc
+hIxtmPOhqDKHH0As113sjTqqo20Ik233x9FFeTFD8Or7ahpqjiv5YCufk9AoQbC
xMIjrK9RkQYgW4RycgvXGASobwN8EE+OsMcyMUER/pdCtQhTQCc1jYLt85VhfEkC
4k9szMB8eZrdV9re/Ku6vnCeXRR5yn2NWKO88U4HfxEpJv5s2uFJi37+x/v9w7Uh
+864W/9NexXg/JFNsvh0Kmxsbi3ZegaouLyrMCHwSA3ByBZ2yCf2VuFPyUCNEZOH
Owi0oc9TgY1yopjsTneyGaMCAwEAAQ==
-----END PUBLIC KEY-----

podman run --rm gcr.io/go-containerregistry/crane digest --platform linux/amd64 --full-ref registry.suse.com/bci/openjdk:21


registry.suse.com/suse/sle15@sha256:fb0f9b6d3c5836af482ab2fddc5f69206ebf4b9189e8c6e1d4ab8efb944c8ddf

podman run --rm -v /tmp/suse.pem:/tmp/suse.pem docker.io/bitnami/cosign verify-attestation \
   --key=/tmp/suse.pem --type spdxjson \
   registry.suse.com/suse/sle15@sha256:fb0f9b6d3c5836af482ab2fddc5f69206ebf4b9189e8c6e1d4ab8efb944c8ddf \
   | jq '.payload' | tr -d '"'| base64 -d | jq '.predicate'

----

