name: Build readme


on:

  push:
    paths:
      - readme-source.adoc
    branches:
      - '**'


jobs:

  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Install asciidoctor-reducer
        run: sudo gem install asciidoctor-reducer --pre

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Reduce readme
        run: 
          - echo -e "\n=TIL\n:source-highlighter: rouge\n\nToday in learned.\n\n:toc:\n" > readme-source.adoc; for i in $(find . -name  '*.adoc' | grep -v README.adoc | cut -c3-) ; do NAME=${i%%.adoc}  ; echo $NAME ; done |sort| awk '{print "include::"$1".adoc["$i"]\n"}' >> readme-source.adoc 
          - asciidoctor-reducer -o README.adoc readme-source.adoc

      - name: Commit readme
        uses: EndBug/add-and-commit@v9
        with: 
          default_author: github_actions
