name: Build readme


on:

  push:
    paths: 
      - adoc/*
    branches:
      - '**'


jobs:

  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Install asciidoctor-reducer
        run: sudo gem install asciidoctor-reducer --pre

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate readme source
        run: bash make-readme-source.sh

      - name: Reduce readme
        run: asciidoctor-reducer -o README.adoc readme-source.adoc

      - name: Commit readme
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
